# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cart.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncart.proto\x12\x04\x63\x61rt\"7\n\x08\x43\x61rtItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"?\n\x0e\x41\x64\x64ItemRequest\x12\x0f\n\x07\x63\x61rt_id\x18\x01 \x01(\x05\x12\x1c\n\x04item\x18\x02 \x01(\x0b\x32\x0e.cart.CartItem\"5\n\x11RemoveItemRequest\x12\x0f\n\x07\x63\x61rt_id\x18\x01 \x01(\x05\x12\x0f\n\x07item_id\x18\x02 \x01(\x05\"!\n\x0eGetCartRequest\x12\x0f\n\x07\x63\x61rt_id\x18\x01 \x01(\x05\"`\n\x0c\x43\x61rtResponse\x12\x0f\n\x07\x63\x61rt_id\x18\x01 \x01(\x05\x12\x1d\n\x05items\x18\x02 \x03(\x0b\x32\x0e.cart.CartItem\x12 \n\x06status\x18\x03 \x01(\x0e\x32\x10.cart.CartStatus*)\n\nCartStatus\x12\n\n\x06\x41\x43TIVE\x10\x00\x12\x0f\n\x0b\x43HECKED_OUT\x10\x01\x32\xb2\x01\n\x0b\x43\x61rtService\x12\x33\n\x07\x41\x64\x64Item\x12\x14.cart.AddItemRequest\x1a\x12.cart.CartResponse\x12\x39\n\nRemoveItem\x12\x17.cart.RemoveItemRequest\x1a\x12.cart.CartResponse\x12\x33\n\x07GetCart\x12\x14.cart.GetCartRequest\x1a\x12.cart.CartResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARTSTATUS']._serialized_start=330
  _globals['_CARTSTATUS']._serialized_end=371
  _globals['_CARTITEM']._serialized_start=20
  _globals['_CARTITEM']._serialized_end=75
  _globals['_ADDITEMREQUEST']._serialized_start=77
  _globals['_ADDITEMREQUEST']._serialized_end=140
  _globals['_REMOVEITEMREQUEST']._serialized_start=142
  _globals['_REMOVEITEMREQUEST']._serialized_end=195
  _globals['_GETCARTREQUEST']._serialized_start=197
  _globals['_GETCARTREQUEST']._serialized_end=230
  _globals['_CARTRESPONSE']._serialized_start=232
  _globals['_CARTRESPONSE']._serialized_end=328
  _globals['_CARTSERVICE']._serialized_start=374
  _globals['_CARTSERVICE']._serialized_end=552
# @@protoc_insertion_point(module_scope)
