# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendation.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import product_pb2 as product__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14recommendation.proto\x1a\rproduct.proto\"a\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\"\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\x10.ProductCategory\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"4\n\x16RecommendationResponse\x12\x1a\n\x08products\x18\x01 \x03(\x0b\x32\x08.Product2U\n\x15RecommendationService\x12<\n\tRecommend\x12\x16.RecommendationRequest\x1a\x17.RecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=39
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=136
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=138
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=190
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=192
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=277
# @@protoc_insertion_point(module_scope)
